# Generated by Django 5.2.4 on 2025-07-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_eliminated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr.qrcode')),
            ],
        ),
    ]
