# Generated by Django 5.2.4 on 2025-07-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_qrcode_is_eliminated_qrscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
