# Generated by Django 5.2.4 on 2025-07-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_qrcode_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
