# Generated by Django 5.2.4 on 2025-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_qrcode_qr_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='is_eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
