# Generated by Django 5.2.4 on 2025-07-07 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_alter_qrcode_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='created_by',
        ),
    ]
