# Generated by Django 5.2.4 on 2025-07-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_remove_qrcode_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='nombre_qr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
